name: sport_news
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


flutter_intl:
  enabled: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  logger: ^1.3.0
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.1
  firebase_remote_config: ^4.2.3
  auto_route: ^7.4.0
  injectable: ^2.1.1
  get_it: ^7.6.0
  flutter_native_splash: ^2.3.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  flutter_inappwebview: ^5.7.2+3
  flutter_offline: ^2.1.0
  flutter_svg: ^2.0.7
  device_info_plus: ^9.0.2
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  yaml: ^3.1.1
  dio: ^5.2.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/config/